name: Start and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install prequisites
      run: npm i
    - name: Start server
      run: npm start
    - name: Test APIs
      run: npm test
